# -*- coding: utf-8 -*-
"""
Created on Tue Jun  4 11:40:41 2024

@author: Utilisateur
"""

from scipy.optimize import least_squares
import numpy as np

# Définir les constantes (à remplacer par vos valeurs spécifiques)

Angles_réél_projecteur=[[-np.arctan(1/9)-11*np.pi/90,np.pi/2+np.arctan(11/np.sqrt(82))],[np.pi/2+np.arctan(1/9)-np.pi/9,np.pi/2+np.arctan(11/np.sqrt(82))],[5*np.pi/36,np.pi/2+np.arctan(11/(9*np.sqrt(2)))]] #Angle du projecteur sur la bouteille 1 [pan_bouteille1,tilt_bouteille1], puis angle du projecteur sur la bouteille 2...

positions_bouteilles=[[10,0,0],[0,10,0],[10,10,0]] #postion x_B1,y_B1,z_B1 de la première bouteille, puis de la deuxième etc... 

position_theorique_projecteur=[0,0,10] # postion théorique du projecteur dans l'espace



"""
x[0] représente delta_x
x[1] représente delta_y
x[2] représente delta_z
x[3] représente delta_alpha
x[4] représente delta_beta"""

def fonction_finale(Angles_réél_projecteur,positions_bouteilles,position_theorique_projecteur):
    pan1,tilt1= Angles_réél_projecteur[0]
    pan2,tilt2= Angles_réél_projecteur[1]
    pan3,tilt3= Angles_réél_projecteur[2]
    x_B1,y_B1,z_B1= positions_bouteilles[0]
    x_B2,y_B2,z_B2= positions_bouteilles[1]
    x_B3,y_B3,z_B3= positions_bouteilles[2]
    x_t,y_t,z_t=position_theorique_projecteur
    x0=np.array([2.0,2.0,1.0,np.pi/9,0])
    #x0 = np.zeros(5)
    #x0=np.array([x_t,y_t,z_t,0.1,0.1])
    #print(pan1)
    def system_of_equations(x):
        f1p = np.tan(pan1)+((x_B1-x_t-x[0])*np.sin(x[3])-(y_B1-y_t-x[1])*np.cos(x[3]))/(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))
        f1t = np.cos(tilt1)-(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        f2p = np.tan(pan2)+((x_B2-x_t-x[0])*np.sin(x[3])-(y_B2-y_t-x[1])*np.cos(x[3]))/(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))
        f2t = np.cos(tilt2)-(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        f3p = np.tan(pan3)+((x_B3-x_t-x[0])*np.sin(x[3])-(y_B3-y_t-x[1])*np.cos(x[3]))/(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))
        f3t = np.cos(tilt3)-(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        return [f1p, f1t, f2p, f2t, f3p, f3t]
    def jacobian(x):
        
        df1p_dx = (-(y_B1-y_t-x[1])*np.cos(x[4])+(z_B1-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
        df1p_dy = ((x_B1-x_t-x[0])*np.cos(x[4])+ (y_B1-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B1-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
        df1p_dz = (-(x_B1-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B1-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
        df1p_dAlpha = (((x_B1-x_t-x[0])**2+(y_B1-y_t-x[1])**2)*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4])*((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3])))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
        df1p_dBeta = (((x_B1-x_t-x[0])**2+(y_B1-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B1-x_t-x[0])*(y_B1-y_t-x[1])*np.sin(x[4])-(z_B1-z_t-x[2])*np.cos(x[4])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3])))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
        
        df1t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        df1t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        df1t_dz = (np.cos(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        df1t_dAlpha = (((x_B1-x_t-x[0])*np.sin(x[3])-(y_B1-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*(((-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+(-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        df1t_dBeta = (((-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B1-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((((-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B1-z_t-x[2])*np.cos(x[4]))*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        
        
        
        df2p_dx = (-(y_B2-y_t-x[1])*np.cos(x[4])+(z_B2-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
        df2p_dy = ((x_B2-x_t-x[0])*np.cos(x[4])+ (y_B2-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B2-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
        df2p_dz = (-(x_B2-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B2-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
        df2p_dAlpha = (((x_B2-x_t-x[0])**2+(y_B2-y_t-x[1])**2)*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4])*((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3])))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
        df2p_dBeta = (((x_B2-x_t-x[0])**2+(y_B2-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B2-x_t-x[0])*(y_B2-y_t-x[1])*np.sin(x[4])-(z_B2-z_t-x[2])*np.cos(x[4])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3])))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
        
        df2t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        df2t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        df2t_dz = (np.cos(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        df2t_dAlpha = (((x_B2-x_t-x[0])*np.sin(x[3])-(y_B2-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*(((-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+(-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        df2t_dBeta = (((-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B2-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((((-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B2-z_t-x[2])*np.cos(x[4]))*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        
        
        
        df3p_dx = (-(y_B3-y_t-x[1])*np.cos(x[4])+(z_B3-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
        df3p_dy = ((x_B3-x_t-x[0])*np.cos(x[4])+ (y_B3-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B3-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
        df3p_dz = (-(x_B3-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B3-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
        df3p_dAlpha = (((x_B3-x_t-x[0])**2+(y_B3-y_t-x[1])**2)*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4])*((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3])))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
        df3p_dBeta = (((x_B3-x_t-x[0])**2+(y_B3-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B3-x_t-x[0])*(y_B3-y_t-x[1])*np.sin(x[4])-(z_B3-z_t-x[2])*np.cos(x[4])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3])))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
        
        df3t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        df3t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        df3t_dz = (np.cos(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        df3t_dAlpha = (((x_B3-x_t-x[0])*np.sin(x[3])-(y_B3-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*(((-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+(-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        df3t_dBeta = (((-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B3-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((((-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B3-z_t-x[2])*np.cos(x[4]))*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        
        return np.array([
            [df1p_dx, df1p_dy, df1p_dz, df1p_dAlpha, df1p_dBeta],
            [df1t_dx, df1t_dy, df1t_dz, df1t_dAlpha, df1t_dBeta],
            [df2p_dx, df2p_dy, df2p_dz, df2p_dAlpha, df2p_dBeta],
            [df2t_dx, df2t_dy, df2t_dz, df2t_dAlpha, df2t_dBeta],
            [df3p_dx, df3p_dy, df3p_dz, df3p_dAlpha, df3p_dBeta],
            [df3t_dx, df3t_dy, df3t_dz, df3t_dAlpha, df3t_dBeta]
        ])
    #res = least_squares(system_of_equations, x0, jac=jacobian,method='lm')
    res = least_squares(system_of_equations, x0,method='lm')
    #rajouter bounds=[[-3,3],[3,3],[3,3],[-1,1],[-1,1]]
    return(res.x,res.cost,res.fun,res.message,system_of_equations([1,1,1,np.pi/9,0]))


    

"""
# Définir le système d'équations non linéaires
def system_of_equations(x,pan1,tilt1,pan2,tilt2,pan3,tilt3,x_B1,y_B1,z_B1,x_B2,y_B2,z_B2,x_B3,y_B3,z_B3,x_t,y_t,z_t):
    f1p = np.tan(pan1)+((x_B1-x_t-x[0])*np.sin(x[3])-(y_B1-y_t-x[1])*np.cos(x[3]))/(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))
    f1t = np.cos(tilt1)-(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    f2p = np.tan(pan2)+((x_B2-x_t-x[0])*np.sin(x[3])-(y_B2-y_t-x[1])*np.cos(x[3]))/(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))
    f2t = np.cos(tilt2)-(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    f3p = np.tan(pan3)+((x_B3-x_t-x[0])*np.sin(x[3])-(y_B3-y_t-x[1])*np.cos(x[3]))/(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))
    f3t = np.cos(tilt3)-(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    return [f1p, f1t, f2p, f2t, f3p, f3t]

# Définir les dérivées partielles (Jacobian)
def jacobian(x,pan1,tilt1,pan2,tilt2,pan3,tilt3,x_B1,y_B1,z_B1,x_B2,y_B2,z_B2,x_B3,y_B3,z_B3,x_t,y_t,z_t):
    
    df1p_dx = (-(y_B1-y_t-x[1])*np.cos(x[4])+(z_B1-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
    df1p_dy = ((x_B1-x_t-x[0])*np.cos(x[4])+ (y_B1-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B1-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
    df1p_dz = (-(x_B1-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B1-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
    df1p_dAlpha = (((x_B1-x_t-x[0])**2+(y_B1-y_t-x[1])**2)*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4])*((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3])))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
    df1p_dBeta = (((x_B1-x_t-x[0])**2+(y_B1-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B1-x_t-x[0])*(y_B1-y_t-x[1])*np.sin(x[4])-(z_B1-z_t-x[2])*np.cos(x[4])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3])))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
    
    df1t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    df1t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    df1t_dz = (np.cos(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    df1t_dAlpha = (((x_B1-x_t-x[0])*np.sin(x[3])-(y_B1-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*(((-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+(-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    df1t_dBeta = (((-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B1-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((((-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B1-z_t-x[2])*np.cos(x[4]))*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    
    
    
    df2p_dx = (-(y_B2-y_t-x[1])*np.cos(x[4])+(z_B2-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
    df2p_dy = ((x_B2-x_t-x[0])*np.cos(x[4])+ (y_B2-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B2-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
    df2p_dz = (-(x_B2-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B2-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
    df2p_dAlpha = (((x_B2-x_t-x[0])**2+(y_B2-y_t-x[1])**2)*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4])*((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3])))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
    df2p_dBeta = (((x_B2-x_t-x[0])**2+(y_B2-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B2-x_t-x[0])*(y_B2-y_t-x[1])*np.sin(x[4])-(z_B2-z_t-x[2])*np.cos(x[4])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3])))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
    
    df2t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    df2t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    df2t_dz = (np.cos(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    df2t_dAlpha = (((x_B2-x_t-x[0])*np.sin(x[3])-(y_B2-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*(((-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+(-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    df2t_dBeta = (((-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B2-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((((-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B2-z_t-x[2])*np.cos(x[4]))*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    
    
    
    df3p_dx = (-(y_B3-y_t-x[1])*np.cos(x[4])+(z_B3-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
    df3p_dy = ((x_B3-x_t-x[0])*np.cos(x[4])+ (y_B3-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B3-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
    df3p_dz = (-(x_B3-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B3-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
    df3p_dAlpha = (((x_B3-x_t-x[0])**2+(y_B3-y_t-x[1])**2)*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4])*((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3])))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
    df3p_dBeta = (((x_B3-x_t-x[0])**2+(y_B3-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B3-x_t-x[0])*(y_B3-y_t-x[1])*np.sin(x[4])-(z_B3-z_t-x[2])*np.cos(x[4])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3])))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
    
    df3t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    df3t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    df3t_dz = (np.cos(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    df3t_dAlpha = (((x_B3-x_t-x[0])*np.sin(x[3])-(y_B3-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*(((-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+(-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    df3t_dBeta = (((-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B3-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((((-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B3-z_t-x[2])*np.cos(x[4]))*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    
    
    return np.array([
        [df1p_dx, df1p_dy, df1p_dz, df1p_dAlpha, df1p_dBeta],
        [df1t_dx, df1t_dy, df1t_dz, df1t_dAlpha, df1t_dBeta],
        [df2p_dx, df2p_dy, df2p_dz, df2p_dAlpha, df2p_dBeta],
        [df2t_dx, df2t_dy, df2t_dz, df2t_dAlpha, df2t_dBeta],
        [df3p_dx, df3p_dy, df3p_dz, df3p_dAlpha, df3p_dBeta],
        [df3t_dx, df3t_dy, df3t_dz, df3t_dAlpha, df3t_dBeta]
    ])

# Valeurs initiales pour les variables inconnues
x0 = np.zeros(5)    #il faudrait réflechir à un point de départ intelligent avec les information que l'on a 
#peut etre x0=np.array([x_t,y_t,z_t,alpha_t,Beta_t])
# Résolution du système au sens des moindres carrés
res = least_squares(system_of_equations, x0, jac=jacobian)

print("Solution : ", res.x)
print("Coût : ", res.cost)
print("Résidus : ", res.fun)
print("Jacobian : ", res.jac)"""

res = fonction_finale(Angles_réél_projecteur,positions_bouteilles,position_theorique_projecteur)
print(res[0])

