# -*- coding: utf-8 -*-
"""
Created on Tue Jun  4 11:40:41 2024

@author: Utilisateur
"""

from scipy.optimize import least_squares
import numpy as np
from scipy.optimize import differential_evolution

def tilt_theo_to_real(tilt):
    tilt_real = 0.8277 * tilt + 2.8336
    return tilt_real


def tilt_real_to_theo(tilt):
    tilt_theo = 1.2082 * tilt - 3.4236
    return tilt_theo





"""
x[0] représente delta_x
x[1] représente delta_y
x[2] représente delta_z
x[3] représente delta_alpha
x[4] représente delta_beta"""

def fonction_finale(Angles_réél_projecteur,positions_bouteilles,position_theorique_projecteur):
    pan1,tilt1= Angles_réél_projecteur[0]
    pan2,tilt2= Angles_réél_projecteur[1]
    pan3,tilt3= Angles_réél_projecteur[2]
    x_B1,y_B1,z_B1= positions_bouteilles[0]
    x_B2,y_B2,z_B2= positions_bouteilles[1]
    x_B3,y_B3,z_B3= positions_bouteilles[2]
    x_t,y_t,z_t=position_theorique_projecteur
    # angle to radian
    pan1 = np.radians(pan1)
    pan2 = np.radians(pan2)
    pan3 = np.radians(pan3)
    tilt1 = np.radians(tilt1)
    tilt2 = np.radians(tilt2)
    tilt3 = np.radians(tilt3)
    #x0=np.array([2.0,2.0,1.0,np.pi/9,0])
    #x0 = np.zeros(5)
    x0=np.array([x_t,y_t,z_t,0.01,0.01])
    #print(pan2)
    def system_of_equations(x):
        f1p = np.tan(pan1)+((x_B1-x_t-x[0])*np.sin(x[3])-(y_B1-y_t-x[1])*np.cos(x[3]))/(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))
        f1t = np.cos(tilt1)-(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        f2p = np.tan(pan2)+((x_B2-x_t-x[0])*np.sin(x[3])-(y_B2-y_t-x[1])*np.cos(x[3]))/(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))
        f2t = np.cos(tilt2)-(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        f3p = np.tan(pan3)+((x_B3-x_t-x[0])*np.sin(x[3])-(y_B3-y_t-x[1])*np.cos(x[3]))/(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))
        f3t = np.cos(tilt3)-(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        return [f1p, f1t, f2p, f2t, f3p, f3t]
    def system_of_equations1(x):
        f1p = np.tan(pan1)+((x_B1-x_t-x[0])*np.sin(x[3])-(y_B1-y_t-x[1])*np.cos(x[3]))/(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))
        f1t = np.cos(tilt1)-(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        f2p = np.tan(pan2)+((x_B2-x_t-x[0])*np.sin(x[3])-(y_B2-y_t-x[1])*np.cos(x[3]))/(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))
        f2t = np.cos(tilt2)-(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        f3p = np.tan(pan3)+((x_B3-x_t-x[0])*np.sin(x[3])-(y_B3-y_t-x[1])*np.cos(x[3]))/(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))
        f3t = np.cos(tilt3)-(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        return np.sum(np.array([f1p, f1t, f2p, f2t, f3p, f3t]) ** 2)
    def jacobian(x):
        
        df1p_dx = (-(y_B1-y_t-x[1])*np.cos(x[4])+(z_B1-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
        df1p_dy = ((x_B1-x_t-x[0])*np.cos(x[4])+ (y_B1-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B1-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
        df1p_dz = (-(x_B1-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B1-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
        df1p_dAlpha = (((x_B1-x_t-x[0])**2+(y_B1-y_t-x[1])**2)*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4])*((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3])))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
        df1p_dBeta = (((x_B1-x_t-x[0])**2+(y_B1-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B1-x_t-x[0])*(y_B1-y_t-x[1])*np.sin(x[4])-(z_B1-z_t-x[2])*np.cos(x[4])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3])))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
        
        df1t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        df1t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        df1t_dz = (np.cos(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        df1t_dAlpha = (((x_B1-x_t-x[0])*np.sin(x[3])-(y_B1-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*(((-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+(-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        df1t_dBeta = (((-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B1-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((((-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B1-z_t-x[2])*np.cos(x[4]))*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
        
        
        
        df2p_dx = (-(y_B2-y_t-x[1])*np.cos(x[4])+(z_B2-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
        df2p_dy = ((x_B2-x_t-x[0])*np.cos(x[4])+ (y_B2-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B2-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
        df2p_dz = (-(x_B2-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B2-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
        df2p_dAlpha = (((x_B2-x_t-x[0])**2+(y_B2-y_t-x[1])**2)*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4])*((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3])))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
        df2p_dBeta = (((x_B2-x_t-x[0])**2+(y_B2-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B2-x_t-x[0])*(y_B2-y_t-x[1])*np.sin(x[4])-(z_B2-z_t-x[2])*np.cos(x[4])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3])))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
        
        df2t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        df2t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        df2t_dz = (np.cos(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        df2t_dAlpha = (((x_B2-x_t-x[0])*np.sin(x[3])-(y_B2-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*(((-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+(-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        df2t_dBeta = (((-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B2-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((((-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B2-z_t-x[2])*np.cos(x[4]))*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
        
        
        
        df3p_dx = (-(y_B3-y_t-x[1])*np.cos(x[4])+(z_B3-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
        df3p_dy = ((x_B3-x_t-x[0])*np.cos(x[4])+ (y_B3-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B3-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
        df3p_dz = (-(x_B3-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B3-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
        df3p_dAlpha = (((x_B3-x_t-x[0])**2+(y_B3-y_t-x[1])**2)*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4])*((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3])))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
        df3p_dBeta = (((x_B3-x_t-x[0])**2+(y_B3-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B3-x_t-x[0])*(y_B3-y_t-x[1])*np.sin(x[4])-(z_B3-z_t-x[2])*np.cos(x[4])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3])))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
        
        df3t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        df3t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        df3t_dz = (np.cos(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        df3t_dAlpha = (((x_B3-x_t-x[0])*np.sin(x[3])-(y_B3-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*(((-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+(-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        df3t_dBeta = (((-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B3-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((((-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B3-z_t-x[2])*np.cos(x[4]))*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
        
        return np.array([
            [df1p_dx, df1p_dy, df1p_dz, df1p_dAlpha, df1p_dBeta],
            [df1t_dx, df1t_dy, df1t_dz, df1t_dAlpha, df1t_dBeta],
            [df2p_dx, df2p_dy, df2p_dz, df2p_dAlpha, df2p_dBeta],
            [df2t_dx, df2t_dy, df2t_dz, df2t_dAlpha, df2t_dBeta],
            [df3p_dx, df3p_dy, df3p_dz, df3p_dAlpha, df3p_dBeta],
            [df3t_dx, df3t_dy, df3t_dz, df3t_dAlpha, df3t_dBeta]
        ])
    bounds = [(x_t-3,x_t+3),(y_t-3,y_t+3),(z_t-3,z_t+3),(-np.pi/2,np.pi/2),(-np.pi/2,np.pi/2)]
    result = differential_evolution(system_of_equations1, bounds)
    #res = least_squares(system_of_equations, x0, jac=jacobian,method='lm')
    res = least_squares(system_of_equations, x0,method='lm')
    #res = least_squares(system_of_equations, result.x,bounds=([x_t-30, y_t-30, z_t-30, -np.pi/2, -np.pi/2], [x_t+30, y_t+30, z_t+30, np.pi/2, np.pi/2]),method='trf')
    #rajouter bounds=[[-3,3],[3,3],[3,3],[-1,1],[-1,1]]
    return(res.x,res.cost,res.fun,res.message,system_of_equations([1,1,1,np.pi/9,0]))
    #return([0.5,0,0,0,0],res.cost,res.fun,res.message,system_of_equations([1,1,1,np.pi/9,0]))


    

"""
# Définir le système d'équations non linéaires
def system_of_equations(x,pan1,tilt1,pan2,tilt2,pan3,tilt3,x_B1,y_B1,z_B1,x_B2,y_B2,z_B2,x_B3,y_B3,z_B3,x_t,y_t,z_t):
    f1p = np.tan(pan1)+((x_B1-x_t-x[0])*np.sin(x[3])-(y_B1-y_t-x[1])*np.cos(x[3]))/(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))
    f1t = np.cos(tilt1)-(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    f2p = np.tan(pan2)+((x_B2-x_t-x[0])*np.sin(x[3])-(y_B2-y_t-x[1])*np.cos(x[3]))/(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))
    f2t = np.cos(tilt2)-(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    f3p = np.tan(pan3)+((x_B3-x_t-x[0])*np.sin(x[3])-(y_B3-y_t-x[1])*np.cos(x[3]))/(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))
    f3t = np.cos(tilt3)-(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    return [f1p, f1t, f2p, f2t, f3p, f3t]

# Définir les dérivées partielles (Jacobian)
def jacobian(x,pan1,tilt1,pan2,tilt2,pan3,tilt3,x_B1,y_B1,z_B1,x_B2,y_B2,z_B2,x_B3,y_B3,z_B3,x_t,y_t,z_t):
    
    df1p_dx = (-(y_B1-y_t-x[1])*np.cos(x[4])+(z_B1-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
    df1p_dy = ((x_B1-x_t-x[0])*np.cos(x[4])+ (y_B1-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B1-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
    df1p_dz = (-(x_B1-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B1-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
    df1p_dAlpha = (((x_B1-x_t-x[0])**2+(y_B1-y_t-x[1])**2)*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4])*((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3])))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
    df1p_dBeta = (((x_B1-x_t-x[0])**2+(y_B1-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B1-x_t-x[0])*(y_B1-y_t-x[1])*np.sin(x[4])-(z_B1-z_t-x[2])*np.cos(x[4])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3])))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2)
    
    df1t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    df1t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    df1t_dz = (np.cos(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    df1t_dAlpha = (((x_B1-x_t-x[0])*np.sin(x[3])-(y_B1-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*(((-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+(-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    df1t_dBeta = (((-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B1-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))*((((-(x_B1-x_t-x[0])*np.cos(x[3])-(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B1-z_t-x[2])*np.cos(x[4]))*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))*(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B1-z_t-x[2])*np.sin(x[4]))**2+(-(x_B1-x_t-x[0])*np.sin(x[3])+(y_B1-y_t-x[1])*np.cos(x[3]))**2+(((x_B1-x_t-x[0])*np.cos(x[3])+(y_B1-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B1-z_t-x[2])*np.cos(x[4]))**2)
    
    
    
    df2p_dx = (-(y_B2-y_t-x[1])*np.cos(x[4])+(z_B2-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
    df2p_dy = ((x_B2-x_t-x[0])*np.cos(x[4])+ (y_B2-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B2-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
    df2p_dz = (-(x_B2-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B2-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
    df2p_dAlpha = (((x_B2-x_t-x[0])**2+(y_B2-y_t-x[1])**2)*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4])*((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3])))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
    df2p_dBeta = (((x_B2-x_t-x[0])**2+(y_B2-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B2-x_t-x[0])*(y_B2-y_t-x[1])*np.sin(x[4])-(z_B2-z_t-x[2])*np.cos(x[4])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3])))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2)
    
    df2t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    df2t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    df2t_dz = (np.cos(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    df2t_dAlpha = (((x_B2-x_t-x[0])*np.sin(x[3])-(y_B2-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*(((-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+(-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    df2t_dBeta = (((-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B2-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))*((((-(x_B2-x_t-x[0])*np.cos(x[3])-(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B2-z_t-x[2])*np.cos(x[4]))*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))*(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B2-z_t-x[2])*np.sin(x[4]))**2+(-(x_B2-x_t-x[0])*np.sin(x[3])+(y_B2-y_t-x[1])*np.cos(x[3]))**2+(((x_B2-x_t-x[0])*np.cos(x[3])+(y_B2-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B2-z_t-x[2])*np.cos(x[4]))**2)
    
    
    
    df3p_dx = (-(y_B3-y_t-x[1])*np.cos(x[4])+(z_B3-z_t-x[2])*np.sin(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
    df3p_dy = ((x_B3-x_t-x[0])*np.cos(x[4])+ (y_B3-y_t-x[1])*2*np.sin(2*x[3])*np.cos(x[4])-(z_B3-z_t-x[2])*np.cos(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
    df3p_dz = (-(x_B3-x_t-x[0])*np.sin(x[3])*np.sin(x[4])+(y_B3-y_t-x[1])*np.cos(x[3])*np.sin(x[4]))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
    df3p_dAlpha = (((x_B3-x_t-x[0])**2+(y_B3-y_t-x[1])**2)*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4])*((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3])))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
    df3p_dBeta = (((x_B3-x_t-x[0])**2+(y_B3-y_t-x[1])**2)*np.sin(x[4])*np.sin(x[3])*np.cos(x[3])-(x_B3-x_t-x[0])*(y_B3-y_t-x[1])*np.sin(x[4])-(z_B3-z_t-x[2])*np.cos(x[4])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3])))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2)
    
    df3t_dx = (np.cos(x[3])*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((-np.cos(x[3])*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+np.sin(x[3])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))-np.cos(x[3])*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    df3t_dy = (np.sin(x[3])*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((-np.sin(x[3])*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))-np.cos(x[3])*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))-np.sin(x[3])*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    df3t_dz = (np.cos(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))-np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    df3t_dAlpha = (((x_B3-x_t-x[0])*np.sin(x[3])-(y_B3-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*(((-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))*np.cos(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+(-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))*np.sin(x[4])*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    df3t_dBeta = (((-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])+(z_B3-z_t-x[2])*np.sin(x[4]))*np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))*((((-(x_B3-x_t-x[0])*np.cos(x[3])-(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])-(z_B3-z_t-x[2])*np.cos(x[4]))*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))*(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4])))/np.sqrt((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)))/((((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.cos(x[4])-(z_B3-z_t-x[2])*np.sin(x[4]))**2+(-(x_B3-x_t-x[0])*np.sin(x[3])+(y_B3-y_t-x[1])*np.cos(x[3]))**2+(((x_B3-x_t-x[0])*np.cos(x[3])+(y_B3-y_t-x[1])*np.sin(x[3]))*np.sin(x[4])+(z_B3-z_t-x[2])*np.cos(x[4]))**2)
    
    
    return np.array([
        [df1p_dx, df1p_dy, df1p_dz, df1p_dAlpha, df1p_dBeta],
        [df1t_dx, df1t_dy, df1t_dz, df1t_dAlpha, df1t_dBeta],
        [df2p_dx, df2p_dy, df2p_dz, df2p_dAlpha, df2p_dBeta],
        [df2t_dx, df2t_dy, df2t_dz, df2t_dAlpha, df2t_dBeta],
        [df3p_dx, df3p_dy, df3p_dz, df3p_dAlpha, df3p_dBeta],
        [df3t_dx, df3t_dy, df3t_dz, df3t_dAlpha, df3t_dBeta]
    ])

# Valeurs initiales pour les variables inconnues
x0 = np.zeros(5)    #il faudrait réflechir à un point de départ intelligent avec les information que l'on a 
#peut etre x0=np.array([x_t,y_t,z_t,alpha_t,Beta_t])
# Résolution du système au sens des moindres carrés
res = least_squares(system_of_equations, x0, jac=jacobian)

print("Solution : ", res.x)
print("Coût : ", res.cost)
print("Résidus : ", res.fun)
print("Jacobian : ", res.jac)"""



if __name__ == "__main__":
    # Définir les constantes (à remplacer par vos valeurs spécifiques)
    
    #test1
    #Angles_réél_projecteur=[[53.55,tilt_theo_to_real(71.75)],[-54.5,tilt_theo_to_real(96.6)],[82.25,tilt_theo_to_real(92.8)]]

    #positions_bouteilles=[[259.8,323.1,254],[330,411,110],[120,819.9,200]] #postion x_B1,y_B1,z_B1 de la première bouteille, puis de la deuxième etc... 

    #position_theorique_projecteur=[0,0,29] # postion théorique du projecteur dans l'espace
    
    #test2
    # Angles_réél_projecteur=[[85.8,tilt_theo_to_real(89.75)],[57.15,tilt_theo_to_real(92.10)],[20.35,tilt_theo_to_real(85.75)]]

    # positions_bouteilles=[[1,6.29,-1.7],[3.42,4.5,-1.3],[3.42,1,-1.2]] #postion x_B1,y_B1,z_B1 de la première bouteille, puis de la deuxième etc... 

    # position_theorique_projecteur=[0,0,-0.29] # postion théorique du projecteur dans l'espace
    
    # coordonnee faux
    #Angles_réél_projecteur=[[85.8,tilt_theo_to_real(89.75)],[57.15,tilt_theo_to_real(92.10)],[20.35,tilt_theo_to_real(85.75)]]

    #positions_bouteilles=[[6.29,1,1.7],[4.5,3.42,1.3],[1,3.42,1.2]] #postion x_B1,y_B1,z_B1 de la première bouteille, puis de la deuxième etc... 

    #position_theorique_projecteur=[0,0,0.29] # postion théorique du projecteur dans l'espace
    #test3
    Angles_réél_projecteur=[[80.20,tilt_theo_to_real(90.23)],[52.65,tilt_theo_to_real(96.5)],[17.9,tilt_theo_to_real(95.15)]]

    positions_bouteilles=[[1,6.29,-1.7],[3.42,4.5,-1.3],[3.42,1,-1.2]] #postion x_B1,y_B1,z_B1 de la première bouteille, puis de la deuxième etc... 

    position_theorique_projecteur=[0,0,-0.29] # postion théorique du projecteur dans l'espace

    print(Angles_réél_projecteur)
    res = fonction_finale(Angles_réél_projecteur,positions_bouteilles,position_theorique_projecteur)
    print(res[0])
    print(f"alpha:{np.degrees(res[0][3])} degree\n")
    print(f"beta:{np.degrees(res[0][4])} degree\n")

    #print()

